version: '3'

services:
  db:
    container_name: forum_postgres
    restart: always
    image: postgres
  api:
    container_name: forum_api
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:@db/postgres
    build: .
    command: >
      bash -c "python3 init_db.py && python3 tests.py && python3 forum.py"
    volumes:
      - .:/forum
    ports:
      - "8000:8000"
    depends_on:
      - db