version: '3'

services:
  db:
    container_name: forum_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PWD}
      - POSTGRES_USER=${USER}
    image: postgres
  api:
    container_name: forum_api
    restart: always
    environment:
      - SANIC_DATABASE_URL=postgresql://${USER}:${PWD}@db/postgres
      - SANIC_PORT=${PORT}
    build: .
    command: >
      bash -c "python3 init_db.py && python3 tests.py && python3 forum.py"
    volumes:
      - .:/forum
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db