version: '3'

services:
  db:
    image: postgres
  api:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    build: .
    command: python3 forum.py
    volumes:
      - .:/forum
    ports:
      - "8000:8000"
    depends_on:
      - db